const fs = require('fs');
const path = require('path');

const targetFile = path.resolve('g:/myProject/shorturl/next-shorturl/src/app/manage/biolink/page.tsx');
let content = fs.readFileSync(targetFile, 'utf8');

// Fix duplicates generated by previous regex
const fixes = [
  { p: /dark:bg-white dark:bg-\[\#111113\]/g, r: 'dark:bg-[#111113]' },
  { p: /dark:bg-slate-50 dark:bg-\[\#18181b\]/g, r: 'dark:bg-[#18181b]' },
  { p: /dark:bg-slate-100 dark:bg-\[\#1e1e24\]/g, r: 'dark:bg-[#1e1e24]' },
  { p: /dark:bg-slate-50 dark:bg-\[\#141417\]/g, r: 'dark:bg-[#141417]' },
  { p: /dark:bg-slate-50 dark:bg-\[\#0f0f0f\]/g, r: 'dark:bg-[#0f0f0f]' },
  
  { p: /dark:border-slate-200 dark:border-white\/5/g, r: 'dark:border-white/5' },
  { p: /dark:border-slate-200 dark:border-white\/10/g, r: 'dark:border-white/10' },
  { p: /dark:bg-slate-100 dark:bg-black\/50/g, r: 'dark:bg-black/50' },
  { p: /dark:bg-slate-50 dark:bg-black\/20/g, r: 'dark:bg-black/20' },
  { p: /dark:bg-slate-100 dark:bg-black\/40/g, r: 'dark:bg-black/40' },
  { p: /dark:bg-slate-900\/40 dark:bg-black\/60/g, r: 'dark:bg-black/60' },
  
  { p: /dark:text-slate-900 dark:text-white/g, r: 'dark:text-white' },
  { p: /dark:text-slate-500 dark:text-zinc-500/g, r: 'dark:text-zinc-500' },
  { p: /dark:text-slate-500 dark:text-zinc-400/g, r: 'dark:text-zinc-400' },
  { p: /dark:text-slate-600 dark:text-zinc-300/g, r: 'dark:text-zinc-300' },
  { p: /dark:hover:bg-slate-100 dark:hover:bg-white\/5/g, r: 'dark:hover:bg-white/5' },
  { p: /dark:hover:bg-slate-200 dark:hover:bg-white\/10/g, r: 'dark:hover:bg-white/10' },
  
  { p: /dark:border-slate-300 dark:border-zinc-700/g, r: 'dark:border-zinc-700' },
  { p: /dark:bg-slate-100 dark:bg-zinc-800\/50/g, r: 'dark:bg-zinc-800/50' },
  { p: /dark:hover:bg-slate-300 dark:hover:bg-zinc-700/g, r: 'dark:hover:bg-zinc-700' },

  // And clean up duplicates that already existed like `dark:text-slate-900 dark:text-white`
  { p: /text-slate-900 dark:text-slate-900 dark:text-white/g, r: 'text-slate-900 dark:text-white' },
  { p: /bg-slate-100 dark:bg-slate-100 dark:bg-black\/40/g, r: 'bg-slate-100 dark:bg-black/40' },
  { p: /border-slate-200 dark:border-slate-200 dark:border-white\/5/g, r: 'border-slate-200 dark:border-white/5' },
  { p: /border-slate-200 dark:border-slate-200 dark:border-white\/10/g, r: 'border-slate-200 dark:border-white/10' },
];

fixes.forEach(({p, r}) => {
  content = content.replace(p, r);
});

// Write it back
fs.writeFileSync(targetFile, content, 'utf8');
console.log('Cleanup complete!');
